services:
  app:
    # restart: always
    ports:
      - "5000:5000"
    # image: ghcr.io/sekai-soft/rss-lambda:latest
    build: .
    volumes:
      - ./blobs:/app/blobs
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
volumes:
  ollama:
